---
- name: Reload Systemd
  systemd:
    daemon_reload: yes
  become: yes
  listen: "Restart Kea DHCP4" 

- name: Restart Kea DHCP4
  service:
    name: kea-dhcp4-server
    state: restarted
    enabled: yes
  become: yes

- name: Restart Kea Ctrl Agent
  service:
    name: kea-ctrl-agent
    state: restarted
    enabled: yes
  become: yes