---
- name: Installer Kea DHCP et d√©pendances
  apt:
    name:
      - kea-dhcp4-server
      - kea-ctrl-agent
      - kea-common
      - apparmor-utils 
    state: present
    update_cache: yes
  become: yes

