---
- name: Installer Kea DHCP et d√©pendances
  apt:
    name:
      - kea-dhcp4-server
      - kea-ctrl-agent
      - kea-common
      - apparmor-utils
      - curl
    state: present
    update_cache: true
  become: true