---
- name: "Configuration et SÃ©curisation des Bastions"
  hosts: ROLE_BAST
  become: true
  vars:
    ha_role: "{{ 'MASTER' if '01' in inventory_hostname else 'BACKUP' }}"
    ha_service_name: "bastion"
    ha_vip_address: "{{ lookup('env', 'TF_VAR_bastion_vip') }}"
    ha_auth_pass: "{{ lookup('env', 'BASTION_PASS') }}"
    ha_router_id: "{{ lookup('env', 'BASTION_ROUTER_ID') | default(51) | int }}"
  roles:
    - common
    - keepalived
